apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dyn-a-go
resources:
  - namespace.yaml
  - deployment.yaml
  - sealedsecret.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: dyn-a-go
images:
  - name: ghcr.io/thefirstofthe300/dyn-a-go
    newTag: 0.2.0
