---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config
  namespace: dyn-a-go
spec:
  encryptedData:
    dyn-a-go.conf: AgAJjfE02MKSAH2gapw2PQzimW/8UBfdo0KlfNPrpEW1TkN3/22itwikp0OfZIDpUaZgCozszGLbQB4GVpuPx669V3Zvom2KSg/1ZCYAoioIG/L40Cn8vaceYg6WxAm793cpvtq/JN4RuT9m4L1ZowOkWQ0mER0SsmSYJ7kMko2MLmXRjVBKXrZbyKUKAZrFLo+RCBvvZpzmxkfLcPXkeEQNCZnGhqH/tdyHl1ETonwvQsRDfgTQ2zYpmRDw0ptf3bC6FNFvOB23rydhaRPzZyfMHj9Jw8wI15x2qE7pLrVQLZS/eEOIsWoK3vOopbbznXE9dUAGsggYnFFC0z9Xs32oy6kkd+mau+B6iRmuS2EXix27fvNsOvP7ebbNy6t/2VdUrfXYOkK4sMk/I1dLoGDloXmhs/6J1FjE6+78yF67xfFFRRwfG/36bfHssK+NKGbXqjwTj2SWu9dzoalvrrMpo/pvlaE4P3vk9AYpyBArwVj/EhGDFyR3AZjVHAekAc7Lsnakn0M/O4p3+NgLnZcFOfMpn14VrX/URXWeux8xGlStaOl6MD8mV1Xr5GmSp8KMbbO4Ux7E77hPxMixRwrsGej+Y0bPLkwhuZLnAKZ1PJI9JnJZYJwBRCqm0Ld0yN6lhFZx6WTk55heY8bgpZP6zD6vu67ICiMgs1jVNk/TyvmO1mO/cTTnvNPZIFeX4xYgBfEtFq2BYQoOlaplEaGdtPeUQNB6wjwKzwCx17NOWQ4pn/OWPp6P8xseKDxbEs37U17dDOYnkV/V/vmfmuCRJQ3NT0K+XxdfntaKnX/+KWbH48/+BZrmGmZ/iTcx+yQXqeV//ULl4Wcx51rx2zr2++K4A3iB82qnNpbYw7HwThGvAsYs49wTn8E5p6LQB3lAh7rVBHr6gfnzmu3izprEdkgbqyPj
  template:
    metadata:
      name: config
      namespace: dyn-a-go
    type: Opaque
