---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config
  namespace: dyn-a-go
spec:
  encryptedData:
    dyn-a-go.conf: AgBheuQwiiZx55l4T3ezG77jvzOHjnLku8QlvNVWxMB+iblPqvhopKnxSTf05XgmSgAHCsg1IgBeg4PUVjmF4VnF5q9JdGxKeD6B+YfLneS3RZIweFTQwoP9mMEgwxnHj4UpvWZ8EZ1Vq4AcIuYf6vnCGbMylyfqoIcxc+orjhwiK8QEAyuzoPjGF5Y3/ldf4ke+HfBgOo+sJxXv7DR1URmEr9z5+qaC2OEKKf8ARCtmhHfx7pcpubNr97cxJfXEPeKidyOb3NNE/EQKoWAQ0aotQzhFHbOXmz+DkJQtaLMBA1m4tBZGP8x5IB/wTm3fchCELyEmOrSo+tTRhrlLukZn2hV0kWRACulYO/FMuUD1jdNHP0QmLyxezl6socr41BYgP+AkutRD7cMf+hykbB7Ea43eOFb9PK2I10ln/F6tUsYmLslFWVoRhyWNzglHkIlBJfTIj7VqLDy+UJUhCgA1mCRunR9njsBxWfD8TCid+aNSDg0NI2/0oUIYHx/jZ6304lZCjqmUgVGrgSqmKzepFsKM02SD7T5/NXm4ivY8oAlyrQ8BpLFb593JUETSeBGdRm14cD6/JRoiazKl12FT9pES6eXqvhKzARcKxiqmq6uZ3Ggjylg988JA3JKyJ4nifQS2WKChEhd6vla0bThNUk3j+V5q5JntGk8lO/dsJrX65EbDRQ81r5ShkIas68eh1Wl/gYymqwoad6QZ2R7Tcbmi+g//dMRlO6K/JJrEbat4wW4jNsBVzkLlze0iDZ6JdT9JqWswPZYPKjX1lDQUKAUcpG7/kQf9d4dBXkTPr0uCWtkfMoeQo18K7bXD//uIRsWpR30uYk2l9Mb+6xPD683CKxbS94nDaFvheazrMs8XPYIqSsKJzB41mYJzcPmxKhWp86SFa4UQmTm19Zm5hBzH1dBO
  template:
    metadata:
      name: config
      namespace: dyn-a-go
    type: Opaque
