---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config
  namespace: dyn-a-go
spec:
  encryptedData:
    dyn-a-go.conf: AgA+jcWU9QAD3WrQu5ynrHS4qC/L8qEGXdDWFLK1fXZZkPGwXTdFfdtUb4Om85oil3v3KTkkmRgk7aBuv5Jrg2jMWWQH5rBNWs8l8SycVsCP8hJ3NBCie7AsOWuBkNcONglA9j/BGl5DsCEGAVJ3JeE9dsKB7pb8S8cApn7erbdnKFwxUUtM1HWrMCQsEsGrl5k5IPbVMUWQtJmnNX+PaPvVMRTTK6TK3Rq1PtdXY9rbXNlpK1YJ5jhmo9E8L8uCnejY7SlODyzCZWqchZpdtFT7zXXQSIjrgWUKLpYkSsxL4l4V0hbRCe0nIoY8Jut9uIKg4WzAIAUf6xw4AxgmaQMSvmbYmbKkNOh1tiTKgweTrJ+Kehk47IHDDOwVDP0vxsmIturLTw1hZBLG9r+fKVTh3uWNXtOjYK9owUXORBVJYYpHN/qHxdCTI6YoDnnJ/Y0Q/H/tD/5J4+mYlW/6YHq9FuMBYvaNNp9QAmYTaP6V7q+uagg1eVklV+dGb1xyXESD12eyHKFW4KAyReecg/oICbeeIMCviqS5/XCfUMVkhkTwN7KV8/4msyXgHDX0VGUr+viLMYbaTedgrKJOh2kK0bzwRO3oUvvRRrLLOgmTh7cmhbkSz03ZErNZBVJ9RX8ctBY2/ifx7iH3VHQ6QXs9Y2Qa7uclcbImTRET8MBJGEePAD56NdRtjevZ4+rma9YwvIRlhlLoP1lqEKug3wXcF+toe9G3HYR+yuZIOFnNSoNEG9QILzO4TuBjgX1CJzzwHkSDdO7W1XFwGWbtp3rFkydQZPDZQfuWo1t99E3LeYBcIuXxchgsapMj/cR2pKgxUjMpEZcYdCpv8liz3EttWL9KxchecDfYRjwWg2c1PVlDrt1LDlwF7/7P2HgYJzz2EMVviV/flygEHnpgCbE+j0R4+v3Y
  template:
    metadata:
      name: config
      namespace: dyn-a-go
    type: Opaque
