---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCLzHs/1kG32mDonaMIFFxBlTrgGh92EDOrdysVXQbDn+39QW7usYTWrsDXq9XVj8wjkFodRF/sRp2wUX+Ci52uJLfRdA02gyH4FRcSWj4QQe1rfG8c9cHBPzxcFvK8f+dLhY1f7KT8cLMk+TG67OnGW/8ffY2VjDRpibK9ug5JXX6775levvX6chPXrj6EMgn8J3FKEtECNhpmYmsI8wkGqOVuKt/m57g18R4LVrzw/HxF7O9gtoqbRxhrWUxfMR2fGeqtS8Xs/c+DLI/Jq2Y9hAHsjwKesUzx/LNNKTN6RT90Do+WdPcS9/n2G6HKJoNN3fHX/cLVolTCs74bLypAz9OuSAtgROpcmF8gHzSrM8Lm+M5e0gF0FQha0st3UhnTvwbim+HVGH9X7kmbnZB+9WJsI/0IZ0pHramSnQqK7Y6lo28PpOF+VAf9rjXVDTqwfIZ11b+MnCJHU6u6EOt9q3ZI/xNfkiBrLC/VtIKlcSstmGQMBMMX7JuzzQyWofmcyVjGdI0H7Svm2204RhAGJuCXrfvMqIfNq/zNEumS7VBLtCr5ANS6kuJe5nXRO+7saMFPWo/wFFrnvNlKZVEHrO/pla0nWZZXg28VKXTnFnmCKuwurB2+Uh6JoUkgL4rT98oN3geakyX4ADsleWPtiHeacRkIlYmwnGbdq+gwqRHqqJ/PBqHPmMpA3AQBuJBOR9KiD/HjcP6y2GWSvifwozNosYEm+60UdSz5UpOCvRjTPYM2RPRp
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
