---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBrM0Ihp0hSdHjA6y9wEDNMKYA7uAnzUTu+nSkQ1yUCxBfCe+J7j3Y0lngsuscG8tKyDsYZINPmQbpnNhrazM/nYBKonp+wV5e4OW2/dP73ljVkyOIMr8Pl5BHVOwNoPPguzuzt3hpJkqBAol54AIGV1mX08s9t9zJBsGPk6u9JEbf9c1BfUvBPOY2XlMJU+8Fohsv/LVdECHYU5LpXRc+Je5gkp6iEhDRY+YHh/LwHUiVUmaRP+ARm4fiyNgLWAOW/Y+X+z3UBVp8v0y7oKZ07+cotNKaKoZRzFk9hr85OBs5VcQronCWGfoIny6htK/qhKVtkmm1pdKj+oyAAefbFc/QBWdwndMzds3v3Rnk4gf2YwBH1c/+8OxWl1XC+MOCY+7tPR+VF9liZk3JYmbkP5ElEwXpY6/Yl6fuq1yVr624kPH6dR0ETOSVBpdN4YEAk5Bx03Scd5Z9i3oM4ygHt+Frmzq3gh8jw5UxhDwYOFNKkptnBCNtjcl0vRGSKD1s0aJcKHdsuO0gyZ7NB0snEOFUM6OSzU7+6i5MMx/dOIqD4/EmoPWDVGf5ieDYswl/9NGx2PL6Et0BFGVayJCY0XFiD6h2CSPhnEiCm0FroIIROoiU9FpbIerHNRnCRdBcGMhvsZHyZLotn7W6m3udVV70eFqkfo+u5IxvUG/dwKGHmGHxlO95SlLMtUPf4YPtyLrZyqTXQGGQAZVi4dJpdoOtAhTeJCfn3bfP7lxlfWw/+bSeKvxO3
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
