---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tubearchivist
  namespace: tubearchivist
data:
  TZ: America/Los_Angeles
  HOST_UID: "568"
  HOST_GID: "568"
  ES_URL: http://192.168.1.204:9200
  REDIS_CON: redis://tubearchivist-redis:6379
  TA_HOST: "https://jellytube.seymour.family *"
  TA_AUTO_UPDATE_YTDLP: release
