---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tubearchivist
  namespace: tubearchivist
data:
  TZ: America/Los_Angeles
  HOST_UID: "568"
  HOST_GID: "568"
  ES_URL: http://192.168.1.204:9200
  REDIS_CON: redis://tubearchivist-redis:6379
  # Set TA_HOST to the Tailscale hostname or IP before first run
  TA_HOST: http://tubearchivist
