---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tubearchivist
  namespace: tubearchivist
spec:
  encryptedData:
    ELASTIC_PASSWORD: AgBXmi0PeLrLCyQsM1Engg4XzOeqbJGMiD8PQmZ8GmEm6zIlHBarcPnYXVy4DWiPvSEoKpffsJh8uLJsz9HNS5pqNxmM8sRggu6UTX9fwjiCU4kaXz2Xe1VwRJzUXiRExZR6hRuZMRdVr5C/tb2cJdMBwWbAMkRgViz0AyWHAm67V8k4/uGX/NEm8k87AtSFUPmMzQmQSb5Nl3oHD/dTxcbG/z3EVF29yPRuVdE4ZRndmUX1ND5afCZSLoUmXpm0z1jqmQbajiWiI72qOU2LrfCodC1Jp1QVwdeI0wNvMCqoojvjW5M0ftnUcJKET8Ol/wRugw6rX5CjoDvK/sKY9IKul76ajkcKNtjrfj2s72fWJ0O/gLssT3Cl7QKmVbXb4AgS0/SnmcdJg23iGYsOs33sIgOpjVrVw1ytCY295iYlcGXYdrbCT07lrjykEYSUs12FijOvzn+rOCFjQnfo4JFS56RmDpC5pS8wD3zpyWcXcsS8EwpMxlmoiKxT1kpAeqCO6pVuTrjSaL8yj8HHbqGt+cuf8Fo32GDl8krngtJPRe3/fNvAaYc3hivOWTEFhGlLTbbqolL6Tc9y8y19ZukNqELngGv3gqIH+HoyIK6GA1XF7Qv8ZWEiqWjl0hbuAYlIXnlCe6S+zqTUdOlj2Jqb7iVWpyaXH8M0go61NTU6NuUxH+Acm0X6qS3FqAQqbbRFamij18qHHQNderemuM6WY3g/tvJN871UJxQMXHOU5g==
    TA_PASSWORD: AgCzkvZG3pfTQAYPsPK4Vi+FB/v+mcVTuTrN5Om4T1pigUtE1Z9FGVfc5rdPo93nyvpvmtgUdWHsbEpCwrHbz6tq+Zw3fs2vuR8ZUCb4XwiV6PYnVUxsRGsyyvRgMhrjAse5XVe4TuDBg7Mq4E2rKvThWBUZhHZmAivmDr2LFEUCtQGuL0nhu3STXgLcvFb4BmNa+KvzNaEt/FDoOmYgoH7HElKFJZ1/VxBLS0ZpLveF5yVICUEtPtD8j0Cd6XmZm9vNbXexKHt1MUuygCqagmV3BlEm8RURUEHwFSIrWb7G3sqi9EtqRpyxsfEyz+KmELcsZDmxqwTu8hjwrJrl+tJQ8QlyB9gt/uFSe49ISCUjttsO8UZSycXf9vi+omqZqm6LLHYUFLUHmvG0tm1fp6MJmor6kVVxhu48OHCn3UGyVoCbERc4ItnOfp9ZZ2rJm5Nu6mq0jC6mG3d4c+wppnPZHYIYASSwMkifIDKyGcAPMzuAH+iQnEHzNs6W6frm5OUP+0FEz+bJmHlSbcOwf2Ie78jeJpHbDotfM5kpJAyyHg3tAbY8e5JnccfGs2SEaJ1zolQ9i1gDGfQiDLKPJN/ethUS7QR31ah74qZlkDqeGR3IWZGyKgBYBSAvvtc4IGjQEVdfFStyWreP3JEdqxi9jEDLpCyz/0uJ/RTjSf2idng3n1u2LDLOEJun00iu3/lu/Ff0uh6lEW9jgZuKnf4IEf1ReyCaectxeIsMY5o8ZA==
  template:
    metadata:
      name: tubearchivist
      namespace: tubearchivist
