---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tubearchivist-media
  namespace: tubearchivist
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/media/data/media
    server: 192.168.1.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: tubearchivist
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: tubearchivist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: truenas-nfs-csi
