---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgCB20Oovn3y0qdBk0MpmhLIPT913Is1HNK67orjLwaisrQ3G1CTYhoraefNDKV/3ZWVraBOP+pX9yIB7JYuWq9DhWUNyx7st6EHkHfwOOPbSuX3JqYZCW88ycIE7Jw+Of4bwJEZbRQudHZm1SoL90V22+yMAc0WKCjSBNhmMgbJECrt6PIEPpUmlUFdJ1ZwLb6SwJ6oPhmIRI7Y6XfwjG7aWP0JNEeXAUXf1hdR88MBCsFZSkew+za4F7W1onx4uBg2L9GO+6sFzzu/mPQ+b5eA9BtXLQaPsys/lCAbMFyy9DkgiDx3inERJJsK5YSsrC8wMrV18QZMTAhXDeAvuGuZY5QrJaRvkbm70gmn7OtTHqn+WgA4ErJGSMnsOFDx5m+kAXvbPlRGd6aClPp+33BGvUicWS8yePpN/aiYJvUfSAGPBQG4Fw++/DZG7TTG6KBd+iNTq5KPmvkX0OdoTEqv+MY7v6SYcu0KjMgXu+UyqAPEyYtn1w1pOdC+mm8GgCikznDUPaC5tiGuiEx4lLPHAGoRMw0zfCeSd8xu0EaecDiAj3utQn2D4V4Zl/KxMEdy5vR2V8ALIzld72NReZVYddzTeLzsqg1m1suAU800HtSKiQPfzypf55QUoxGWejj5YtJysQcrzqcxySof9oyl8CalGK98g8d3hDEslSpLFPb3HH0IzXjYlidhH93HVr1VclFN7spblQMBsy57W4XTzrXOQCoVhRTynlPzoTVg86DVO0u98wdNqoTmCVFe4PSBoV9Da/iwtwyeuGhtP8Ggh9GHC8N/vCZRee3LSPBudsybzInb1p6zBvYb4vB16rGUssYZw9E3Luq0SMCT4lt41OCsnnmJ123NEv8aYJpmacyOLfU6OtLFwH9Q7XcgLpaYHAyJaTi9qescp0kYeQKfBVtmRpvFwRJgoU9y3dlm1aZJxtDvWQAkMuo9qw==
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
