---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgBgT0SD70vDQiKiGrEcsi3R8KxGoaxdB8cZnYRHvxBykEEah/LDTFENlcE6CA0rpCsBR8nWkPylAvyuDmceP394BN0feOyBlzkXNxEEvVJzwWu76+exuGaJ48NCr6A4hbr2lBspuMUSXoTvXZFB9TutrKMnT/TBqvI/o4EO76GyKi71SEwIbQF3WDgrX/lA80NCkq7swAJd4ymjVUkqSOag9epKY11Q0Pd34SpgL2dgYn5/smeJEfhvXvR7tRdyKjtxOT+7U7+qu7BMegLAnGIeReFh4z2CDpPRDmGiIhiaHz456GE2/R73eB7G6jjEuUBGQecY6P3dFkJVdG4mbLoYMLuElMPROwd6uDtiwHn9XfqgCbSckOs7HciJ0cJH0ZbTDLzFsSwB6YSAUZ4uZIS95P2bcLzMPuAOS4XvxfIxDRpT3DRo6XpFuFg8USLbgLRPDGbvUKHmJd2HIRTLPQ3Y9txJpiDYEClyxxQ8XSJzqYQTuaWPehpPk8n7BCxPthDV9JMceeB1GWno7InjbqhFBil40jFDtKCJbRg6hEdUr0cn67noYdwnpFbablnC2mTY5+6sYK9GbLOfP3NvZQtB4uyM7Zl5PaconcUyxYDs6tRafJSwVymo9c4lBlpENssneCyYiseCGxoJ3N/nXE0TnUvw14t4F0mU4lTxAifwCvwhRp0QSgLJ8URbveWxOKsedL7Qtw6CoV/M8wegbDxDSN0Dfvl1OIjop5irxxJBJ+Lc/DqpuINm/cZ7TPz061ZfpwVz9MzjCqQ272Hupx8gmWNMwA6UBLgYOjifbmdvO5h3MuB82x69QoY9Titq0NFbbP8BPA0HdVCFB2lHplfQQ2jzcortDvoe78L55nLKUOgTYqZXev9Bxxl66FhRjZ2L8Syog4vsMkp2nZsdsPUfVT9lBIvQ231NV2gWM1vZuFDpc0dM1orv92PTMg==
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
