---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-values
  namespace: immich
spec:
  encryptedData:
    values.yaml: AgAb3oJDxqGADuJHPGZvIdC2FPP8e/7HQnqJtvdxBW0ubscqWofB//dDvRC9nK3Ab6cacYwd1hECJAOkzM0wiLRAqX/MQyIlsvXYUXlyo0vbtOstOu+DyvzxOIJCbFsYGhqG/e5SxETvcL8VfjW8K5hyNh0z+/B8toLI35tove04J/ZwP7skXO2H/LMJBuerSe/Oz1w1oR5F0nd0+ZaIzBEolSzDD1YMfF/bzgP+bd3TnOyhz6jByb+3X8YcqnInc3iUqlOJ2jfUd9n2UrT2ljuO7XSuFUVqLs5tNgBvrVGibB5lFK2B1l4lzTyifsRYpFSfn+aqUrZKLsUFQ6zpKAViPK1+v7V8YlnxG3+xc2sgfre/oXS/T94T79SAP6rzljI79HiYZz/eUgRbvaxjh3yNJKt+QpiExThkSVFhCIVkAeDqipJ0monW7fzE0SzEU6FJqxYX1SuSehSAbUEHNb9PEgsRO3W4O/LsNmLD/LBXvebjHvVqd4MuxKldgOBgSF8wdwZ4QxSEbOJi45vMkreyRc/CIft38BpWupV+UcMkEEKN+rc9C7d3tJ9jm7ZwPBWPHx1ozNXpVTXj+2z5Dx9gOV8JRFOPehE5a3+7aPxVee8l7w5KkwfS8IqY3w9HdIAKY2Nae+yox6W50S9ClAX68huBd5v0j6Ittl/NiNmz+mQsIV5S59OgMa28XW/WOazKXieV4dyQYN0tSvzrYqjGxPmVBwHLJLX55adL/cRDcwujZQCj2UGNXAF6DZZGvsVXn3T5nYX+tplYJw0aCEkLdWylolEtL5DLHvl9XpEf+U9jhqAubDV+LoQXNr0njeGk0ne1CeFDjVwg8RfM8XuLMJbxauxPVnfeBYR689TqlEhgLmN9C5VLbxluJlpGTuDqrv/N07sNuG9xCsWeRHR/hAoK3+IkoNMz3h+VWDb6FVVKk16CqMxpSyOdkQ==
  template:
    metadata:
      name: immich-values
      namespace: immich
    type: Opaque
